# hostname is fleet-telemetry.lgnat.com:4443 external port 4443 mapped to internal port 8443
services:
  lg-fleet-telemetry:
    container_name: lg-fleet-telemetry
    image: fleet-telemetry-integration-tests:latest
    ports:
      - "8443:8443"
      - "4269:4269"
      - "5284:5284"
      - "9090:9090"
    volumes:
      - ./certs:/certs:ro
      - ./config/timescale-server-config.json:/etc/fleet-telemetry/config.json:ro
      - ./telemetry-data:/data/telemetry
    command: ["/fleet-telemetry", "-config=/etc/fleet-telemetry/config.json"]
    environment:
      - SUPPRESS_TLS_HANDSHAKE_ERROR_LOGGING=true
    restart: unless-stopped

  vehicle-command:
    image: tesla/vehicle-command:latest
    container_name: fleet-telemetry-vehicle-command
    restart: unless-stopped
    ports:
      - "4443:4443"
    volumes:
      - ./certs/tesla-api/proxy/tls-cert.pem:/config/tls-cert.pem:ro
      - ./certs/tesla-api/proxy/tls-key.pem:/config/tls-key.pem:ro
      - ./certs/tesla-api/keys/private-key.pem:/config/fleet-key.pem:ro
    command:
      - "-tls-key=/config/tls-key.pem"
      - "-cert=/config/tls-cert.pem"
      - "-key-file=/config/fleet-key.pem"
      - "-host=0.0.0.0"
      - "-port=4443"
      - "-verbose"
    environment:
      TESLA_VERBOSE: "true"
